# This is a sample settings file. Copy it into your project root.

####################
# General settings start here.

# Some options for the "puppet apply"
# NOTE: "--parser future" is required!
puppet_options:
  --parser future
  --verbose
  --debug

####################
# Project specific settings start here.

# A fixed ip for the VM
internal_ip: 10.10.10.115
hostname: amp-portal-27

# FQDN and aliases
domain: amp-portal-27.dev
aliases:
  - www.amp-portal-27.dev
  - public.amp-portal-27.dev

environment: LOCAL

# Mount the current folder in the project document root.
docroot: /var/www/amp-portal-27

####################
# Database specific settings start here.

mysql_root_password: 'demo#'
mysql_databases:
  - name: public_local
    user: public_user
    pass: 'demo!'
  - name: amp_public_page
    user: public_page_user
    pass: 'demo!'

pgsql_root_password: 'demo#'
pgsql_databases:
  - name: public_local
    user: public_user
    pass: 'demo!'
  - name: amp_local
    user: amp_user
    pass: 'demo!'

####################
# Default vagrant box.
box:
  name: scientific
  url: https://dl.dropboxusercontent.com/s/r4x67n65nn9crch/scientific-20140228.box?dl=1
  download_checksum: 4d55f9e399e3c2d918cb236d29c52b67
  download_checksum_type: md5

# Hiera configuration for puppet. Goes as content into /etc/puppet/hiera.yaml
puppet_hiera_data_folder: /etc/puppet/modules/site/data

# <<<data_folder>>> is a placeholder for $puppet_hiera_data_folder
etc_puppet_hiera_yaml: |
  ---
  :backends:
    - yaml

  :yaml:
    :datadir: <<<data_folder>>>

  :hierarchy:
    - %{fqdn_underscore}
    - %{environment}
    - common

####################
# Manifest and modules for puppet.
puppet_manifest_file_contents: |
  node default {
    # Do some magic!
    class { '::happydev::fairy_dust::water_lily': } ->
    class { '::happydev::rhel': } ->
    class { '::happydev::fairy_dust::orange_blossom': } ->
    class { '::happydev::mysql': } ->
    class { '::happydev::pgsql': } ->
    class { '::happydev::apache_php': }
  }

# Relative or absolute path pointing to the happy-deployer files.
# NOTE: Do NOT add a trailing slash (/).
#happy_deployer_path: /home/user/Downloads/happy-deployer
# happy_deployer_path: ../happy-deployer-local

# The manifest file to use for this project.
# This file should be in the happy-deployer/puppet/manifests folder:
# puppet_manifest_file: ampp.pp
