# This is a sample settings file. Copy it into your project root.

########################################
# Project specific settings.

# VM specific information:
#  - vm_hostonlyip should be unique among your virtual machines.
#  - the VM hostname is created using vm_shortname and vm_environment.
vm_hostonlyip: 10.10.10.10
vm_shortname: the-project
vm_environment: local

# Vhosts and shared folders:
#  - template is the name of the template used to create the vhost.
#  - source points to a folder on the host OS, it can be a relative path.
#  - docroot points to a folder in the gues where source is mounted.
vhosts:
  - domain: the-project.dev
    aliases:
      - www.the-project.dev
    template: default
    source: ./
    docroot: /var/www/the-project
  - domain: another-project.dev
    aliases:
      - www.another-project.dev
    template: alternative
    source: ../another-project
    docroot: /var/www/another-project

####################
# Database specific settings.

# mysql_root_password: 'this_is_a_random_password'
# mysql_databases:
#   - name: main_database
#     user: main_user
#     pass: 'this_is_a_random_generated_password!'

pgsql_allow_remote_access: false
pgsql_root_password: 'this_is_a_random_password'
pgsql_databases:
  - name: main_database
    user: main_user
    pass: 'this_is_a_random_generated_password!'
  - name: seccond_database
    user: seccond_user
    pass: 'this_is_another_random_generated_password!'

# mongo_databases:
#   - name: main_database
#     user: main_user
#     pass: 'this_is_a_random_generated_password!'

########################################
# Vagrant settings.

# Default VM box.
box:
  name: scientific6
  url: http://example.org/files/scientific6.box
  download_checksum: 00000000000000000000000000000000
  download_checksum_type: md5

########################################
# Puppet settings.

# Enable puppet development "mode".
puppet_development: 0

# Default options for the "puppet apply"
# NOTE: "--parser future" is required!
puppet_options:
  --parser future
  --verbose
  --debug

# Development options for the "puppet apply"
# NOTE: "--parser future" is required!
puppet_options_dev:
  --parser future
  --verbose
  --debug

####################
# Puppet settings for non-development mode:
puppet_module_name: SchnWalter/happydev
puppet_module_version: 0.2.8

# HACK-ishly remove existing modules and then reinstall.
puppet_force_reinstall: 0

puppet_manifest_file_contents: |
  node default {
    include ::happydev::rhel
    include ::happydev::fairy_dust::orange_blossom
    include ::happydev::mysql
    include ::happydev::apache
    include ::happydev::php
  }

####################
# Puppet settings for development mode:

# Relative or absolute path pointing to the local development happy-deployer files.
# NOTE: Do NOT add a trailing slash (/).
happy_deployer_path: ../happy-deployer

# Alternative (development) manifest file, located in the puppet/manifests folder inside happy-deployer:
# Replaces puppet_manifest_file_contents only when in puppet development "mode".
puppet_alternative_manifest_file: default.pp
