# This is a sample settings file. Copy it into your project root.

########################################
# Project specific settings.

# A fixed ip for the VM, should be unique.
internal_ip: 10.10.10.10
hostname: the-project

# FQDN and aliases
domain: the-project.dev
aliases:
  - www.the-project.dev

# The type of the environment, not really doing anything at the moment.
project_environment: local

# Mount the current folder in the project document root.
# NOTE: used by config.vm.synced_folder in your Vagrantfile
docroot: /var/www/the-project

####################
# Database specific settings.

# mysql_root_password: 'this_is_a_random_password'
# mysql_databases:
#   - name: main_database
#     user: main_user
#     pass: 'this_is_a_random_generated_password!'

pgsql_root_password: 'this_is_a_random_password'
pgsql_databases:
  - name: main_database
    user: main_user
    pass: 'this_is_a_random_generated_password!'
  - name: seccond_database
    user: seccond_user
    pass: 'this_is_another_random_generated_password!'

########################################
# Vagrant settings.

# Default VM box.
box:
  name: precise64
  url: http://files.vagrantup.com/precise64.box
  download_checksum: 5803ee2fa7c5ded51a59f7928a2fead0
  download_checksum_type: md5

########################################
# Puppet settings.

# Enable puppet development "mode".
puppet_development: 0

# Default options for the "puppet apply"
# NOTE: "--parser future" is required!
puppet_options:
  --parser future
  --verbose

# Development options for the "puppet apply"
# NOTE: "--parser future" is required!
puppet_options_dev:
  --parser future
  --verbose
  --debug

####################
# Puppet settings for non-development mode:
puppet_module_name: SchnWalter/happydev
puppet_module_version: 0.1.4

# HACK-ishly remove existing modules and then reinstall.
puppet_force_reinstall: 0

puppet_manifest_file_contents: |
  node default {
    # Do some magic!
    class { '::happydev::rhel': } ->
    class { '::happydev::fairy_dust::orange_blossom': } ->
    class { '::happydev::fairy_dust::water_lily': } ->
    class { '::happydev::pgsql': } ->
    class { '::happydev::apache_php': }
  }

####################
# Puppet settings for development mode:

# Relative or absolute path pointing to the local development happy-deployer files.
# NOTE: Do NOT add a trailing slash (/).
happy_deployer_path: ../happy-deployer

# Alternative (development) manifest file, located in the puppet/manifests folder inside happy-deployer:
# Replaces puppet_manifest_file_contents only when in puppet development "mode".
puppet_alternative_manifest_file: default.pp
