# Default vagrant settings file.
#
# You can copy this file to "Vagrantsettings.local.yaml" and configure it.
#

########################################
# Project specific settings.

# VM specific information:
#  - vm_hostonlyip should be unique among your virtual machines.
#  - the VM hostname is created using vm_shortname and vm_environment.
vm_hostonlyip: 10.10.10.10
vm_shortname: the-project
vm_environment: local

# Vhosts and shared folders:
#  - template is the name of the template used to create the vhost.
#  - source points to a folder on the host OS, it can be a relative path.
#  - docroot points to a folder in the gues where source is mounted.
vhosts:
  - domain: the-project.dev
    aliases:
      - www.the-project.dev
    template: default
    source: ./
    docroot: /var/www/the-project
  - domain: another-project.dev
    aliases:
      - www.another-project.dev
    template: alternative
    source: ../another-project
    docroot: /var/www/another-project

####################
# Database specific settings.

# mysql_root_password: 'this_is_a_random_password'
# mysql_databases:
#   - name: main_database
#     user: main_user
#     pass: 'this_is_a_random_generated_password!'

pgsql_allow_remote_access: false
pgsql_root_password: 'this_is_a_random_password'
pgsql_databases:
  - name: main_database
    user: main_user
    pass: 'this_is_a_random_generated_password!'
  - name: seccond_database
    user: seccond_user
    pass: 'this_is_another_random_generated_password!'

# mongo_databases:
#   - name: main_database
#     user: main_user
#     pass: 'this_is_a_random_generated_password!'

########################################
# Vagrant settings.

# Default VM box.
box:
  name: scientific7
  url: http://example.org/files/scientific7.box
  download_checksum: 00000000000000000000000000000000
  download_checksum_type: md5

########################################
# Relative or absolute path pointing to the local development happy-deployer files.
# NOTE: Do NOT add a trailing slash (/).
happy_deployer_path: ../happy-deployer
