---
# Default vagrant settings file.
#
# You can copy this file to "Vagrantsettings.local.yml" and configure it.
#
# For more information:
# @see https://github.com/devgateway/happy-deployer
#

# Used to name the VM and set hostname for the GUEST (only if vagrant.hosts_entry is 1).
# TODO: Use `project_environment` to botstrap instances?!?
project_shortname: the-project
project_environment: local

# Vagrant VM only settings.
#  - hostonlyip: should be unique IP among your virtual machines.
#  - hosts_entry: determines if the GUEST hostname is add added to the HOST /etc/hosts file.
vagrant:
  hostonlyip: 10.10.10.10
  hosts_entry: 0

# Define mount points for the VM.
vagrant_volumes:
  - source: ./
    target: /var/www/the-project-local

# Information about the box.
vagrant_box:
  name: scientific7
  url: https://example.org/files/scientific7.box
  download_checksum: 00000000000000000000000000000000
  download_checksum_type: md5

# Ansible variables to override.
common__backups_user: vagrant
common__backups_group: vagrant
httpd__User: vagrant
httpd__Group: vagrant
httpd__User_vhosts: vagrant
httpd__Group_vhosts: vagrant
