---

# Apache Solr port.
# NOTE: The default is: 8983
solr__port: 8983

# The Solr version to download and install.
solr__version: 5.5.2

# The sha256 checksum of the downloaded file.
solr__download_checksum: "md5:ad798c4ddeccd740cf78c25c7962ba71"

# Set the Download mirror, WITH a trailing slash.
solr__download_mirror: https://archive.apache.org/dist/lucene/solr/

# Mirros only offer the latest version.
# @see: http://www.apache.org/dyn/closer.lua/lucene/solr/
# solr__download_mirror: https://www-eu.apache.org/dist/lucene/solr/
# solr__download_mirror: https://www-us.apache.org/dist/lucene/solr/


#### Internal variables:
# @see: https://lucene.apache.org/solr/downloads.html
_solr__package: "solr-{{ solr__version }}"
_solr__download_url: "{{ solr__download_mirror }}{{ solr__version }}/{{ _solr__package }}.tgz"
