---

# TODO: Improve!

# - name: Create temproary directory.
#   command: "mktemp --directory --suffix='--solr'"
#   register: solr_temp_dir

- name: Download Solr
  get_url: url={{ _solr__download_url }} dest=/tmp checksum={{ solr__download_checksum }}
  register: solr_archive

- name: Extract Solr package archive
  unarchive: src={{ solr_archive.dest }} dest=/opt copy=no

- name: Run the Solr install script
  command: "/opt/{{ _solr__package }}/bin/install_solr_service.sh {{ solr_archive.dest }} -p {{ solr__port }} -f"
  args:
    creates: /etc/init.d/solr

- name: Stopping Solr in order to start it using systemd.
  command: service solr stop

- name: Start and Enable Solr using systemd
  service: name=solr state=started enabled=yes
