name 'SchnWalter-happydev'
version '0.2.9'
source 'https://github.com/devgateway/happy-deployer/tree/master/puppet/modules/happydev'
author 'Development Gateway'
license 'MIT'
summary 'Setup a Development Environment'
description 'Quickly creates a basic development environment.'
project_page 'https://github.com/devgateway/happy-deployer'


dependency 'puppetlabs/stdlib', '4.9.0'
dependency 'puppetlabs/concat', '1.2.4'

dependency 'puppetlabs/apache', '1.6.0'
dependency 'puppetlabs/firewall', '1.7.1'

dependency 'example42/php', '2.0.19'
dependency 'example42/puppi', '2.1.12'

dependency 'puppetlabs/mysql', '3.6.1'
dependency 'puppetlabs/postgresql', '4.6.0'
dependency 'puppetlabs/mongodb', '0.11.0'

dependency 'maestrodev/rvm', '1.10.2'
dependency 'jfryman/nginx', '0.2.7'
