name 'SchnWalter-happydev'
version '0.1.5'
source 'https://github.com/devgateway/happy-deployer/tree/master/puppet/modules/happydev'
author 'Development Gateway'
license 'MIT License'
summary 'Setup a Development Environment'
description 'Quickly creates a basic development environment.'
project_page 'https://github.com/devgateway/happy-deployer'


dependency 'puppetlabs/stdlib', '3.2.x'

dependency 'puppetlabs/apache', '1.0.x'
#dependency 'jfryman/nginx', '0.0.9'
dependency 'puppetlabs/firewall', '1.0.x'
dependency 'example42/php', '2.0.x'
dependency 'example42/puppi', '2.1.x'
dependency 'rafaelfc/pear', '1.0.x'

dependency 'puppetlabs/mysql', '2.2.x'
dependency 'puppetlabs/postgresql', '3.3.x'
dependency 'puppetlabs/mongodb', '0.7.x'
dependency 'puppetlabs/concat', '1.0.x'
